channels = ["conda-forge"]

[deps]
python = ">=3.11,<3.12"

[pip.deps]
numpy               = "==2.2.6"
qiskit              = "==2.3.1"
qiskit-aer          = "==0.17.2"
qiskit-ibm-runtime  = "==0.46.1"
qiskit-optimization = "==0.7.0"
scipy               = "==1.15.3"
